### ISSUE TITLE
Incorrect error...?

### ISSUE THREAD

**Issue by joetidee** [xolvio/meteor-jasmine#286]
I am getting the following error in my console when I run my Meteor app. I am using the meteor-publish-composite package:

[sanjo:jasmine]: The file "/tidee/app/tidee-meteor/server/lib/startup.js" has syntax errors. [TypeError: Object [object Object] has no method 'publishComposite']

**Comment by Sanjo** [comment]
Hi, this error comes from the server unit mode. Please upgrade to sanjo:jasmine 0.20.0. Then it will go away because I have disabled the server unit mode in this release by default.
