### ISSUE TITLE
Infinite page refresh using html reporter in browser

### ISSUE THREAD

**Issue by jraede** [xolvio/meteor-jasmine#288]
Steps to reproduce:

1. Create a package that uses `'sanjo:jasmine@0.20.0'` on test
2. Test the package from the root application directory with the following command: `PACKAGE_DIRS=./packages velocity test-package packages/{my-package} --release METEOR@1.2.0.1`
3. Page sometimes refreshes a whole bunch of times in a row before stopping, apparently randomly.

Meteor version 1.2.0.1
Velocity-cli version: 0.3.3

**Comment by aldeed** [comment]
I’ve seen this same issue several times with 0.19.0. I think it was usually when tests finish running and then I click the browser refresh button. You can see the browser tab icon flicker a bunch.

**Comment by Sanjo** [comment]
Yeah, I already identified the source. It comes from an error in my refresh logic that I have introduced recently. Will release a fix soon.
