### ISSUE TITLE
Server Unit tests no longer appear in V0.20.0

### ISSUE THREAD

**Issue by marcmunro** [xolvio/meteor-jasmine#289]
After upgrading to v0.20.0, server unit tests no longer appear to be available.  Downgrading to 0.18.0 resolved this issue.  This can be replicated simply by creating a new meteor project, and adding:

    sanjo:jasmine@=0.20.0
    velocity:html-reporter
to the .meteor packages file.

**Comment by Sanjo** [comment]
Please see the release note: https://github.com/xolvio/meteor-jasmine/blob/master/History.md#0200

**Comment by marcmunro** [comment]
Might be worth making that note prominent in the README, as many tutorials, etc talk about the 4 modes.

Thanks for the quick response tho.

**Comment by Sanjo** [comment]
I have added a note to https://velocity.readme.io/docs/jasmine-testing-modes#section-server-unit-test-mode on release. The server unit mode has been not recommended by me for a while already, because of its current implementation flaws.
