### ISSUE TITLE
Test mode files using patterns

### ISSUE THREAD

**Issue by firebait** [xolvio/meteor-jasmine#290]
Hi,
I wanted to ask a question. I know that there are standard directories for each test mode but I wanted to use angular-meteor with the john papa style guide (https://github.com/johnpapa/angular-styleguide#organizing-tests) and organize my unit tests this way. 
Is there a way to define directories per test mode? or would it be a good idea to do so?

**Comment by Sanjo** [comment]
This is currently not fully implemented. I want this too for unit tests. I think it makes sense for the reasons that John Papa lists.

This feature is tracked with: https://github.com/meteor-velocity/velocity/issues/337.

Let me know if you want to sponsor this feature or help to get it done.

**Comment by firebait** [comment]
Love to sponsor and help with this implementation. I'll comment on the other issue.
