### ISSUE TITLE
package method not defined

### ISSUE THREAD

**Issue by philcruz** [xolvio/meteor-jasmine#294]
I'm trying to write a simple package test. Using the simple example

    it('works', function () {
	expect(it).toBeDefined();
	})

that works fine. But when I try to call a method, validateEmail, that is defined in the package

     it('validate good email', function () {
        var email = "john.doe@gmail.com";
        var result = validateEmail(email);
        expect(result).toBeTruthy();
    })

What am I missing?

**Comment by Sanjo** [comment]
You need to api.use your package in the Package.onTest block. Check out the example: https://github.com/xolvio/meteor-jasmine/blob/master/test-app/packages/package-to-test/package.js

**Comment by Sanjo** [comment]
Also, only exported globals are available I think. You can assign those internals to a <PackageName>Internals exported global.

**Comment by philcruz** [comment]
Ah, thanks. I was working off that example but missed the api.use. I'm now hitting another issue but I'll create another issue if I can't work it out.
