### ISSUE TITLE
Angular tests not working in jasmine/client/integration

### ISSUE THREAD

**Issue by damirkusar** [xolvio/meteor-jasmine#296]
Hi, when testing unit tests and mocking stuff under client/unit, angular stuff works. But the same test under integration, does not work.

things like this are not recognized:
beforeEach(module('catena'));
beforeEach(inject(function ($rootScope, $state, $location) {

more specific, module or inject. 

Do you have a suggestion? I mean, i could pull integration tests also under unit, then it would work..

**Comment by Sanjo** [comment]
I think putting the AngularJS integration tests in the client/unit folder is the best solution.

Otherwise you could maybe get it work if you load the angular mock package via debugOnly: true package.

**Comment by damirkusar** [comment]
Hi Sanjo,

thanks for your reply, so, then I am leaving it in client/unit :)

thanks
