### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by orlade** [xolvio/meteor-jasmine#300]
In the README, "[Learn how to get started with sanjo:jasmine](https://velocity.readme.io/docs/getting-started-with-jasmine)" links to https://velocity.readme.io/docs/getting-started-with-jasmine, but the documentation has been taken down.

It's all well and good to hand testing back to MDG, but do the docs really need to disappear in the meantime? I understand you've got a book to sell, but the link should be changed at least.

**Comment by Sanjo** [comment]
Yeah, I will update the documentation link. It has been forgotten..
