### ISSUE TITLE
Integration tests hanging

### ISSUE THREAD

**Issue by alphashuro** [xolvio/meteor-jasmine#303]
Client unit tests are running fine, but client and server integration tests keep pulsing forever, and nothing is printed out to the integration test log files... The only clue I'm getting is velocity prints "Meteor tools is installing" whenever I try to run it (twice, once for client integration and once for server integration).

Any idea how to fix this problem?

**Comment by alphashuro** [comment]
Figured it out, had to actually clone this repo and manually change velocity:core version used from 0.10.2 to 0.10.8 to make it use meteor 1.2.1 instead of downloading an older version of meteor tools. Isn't this something that can be easily changed to become the default though?

**Comment by Sanjo** [comment]
Yes, I will update the version constraint. I wasn't aware of this issue, because I didn't have this issue so far.

**Comment by Sanjo** [comment]
Fixed with 0.20.3

**Comment by alphashuro** [comment]
Thank you

**Comment by namerci** [comment]
I'm using sanjo:jasmine@0.21.0 and still have same problem. Unit tests works fine, but integrations not.
