### ISSUE TITLE
Jasmine Server Unit tests not being run

### ISSUE THREAD

**Issue by jaskinn** [xolvio/meteor-jasmine#304]
I cannot seem to get the server unit tests to run.

I have the directory structure setup as follows: tests/jasmine/server/unit/

What else do I need to do? All the other tests were run as soon as files appeared in the directory.

**Comment by Sanjo** [comment]
See https://meteor-testing.readme.io/docs/jasmine-testing-modes#section-server-unit-test-mode for the answer.
