### ISSUE TITLE
jasmine-jquery getJSONFixtures() from server side

### ISSUE THREAD

**Issue by superyonjan** [xolvio/meteor-jasmine#308]
My server side calls another api to load data first and then serve to request. I want to test my server method by loading json file as done in client. Any way I can achieve or invoke `getJSONFixtures()` from server? I just want to load test json files for server test

**Comment by Sanjo** [comment]
You can use HTTP.get on the server side to request the fixtures in the same way as you do with getJSONFixtures() on the client (-> via HTTP get request).

http://docs.meteor.com/#/full/http_get
