### ISSUE TITLE
Package export

### ISSUE THREAD

**Issue by vangorra** [xolvio/meteor-jasmine#313]
Exports defined in api.export() are undefined in tests.

This is a simple project that demonstrates the issue:
``` bash
git clone https://github.com/prime-8-consulting/velocity-teamcity-reporter
cd velocity-teamcity-reporter
npm install velocity-cli -g
velocity test-package ./ --velocity
```

Looking at test.js, you'll notice we have to manually get the exported class. Via:
``` javascript
var TeamCityReporter = Package['prime8consulting:velocity-teamcity-reporter']['TeamCityReporter'];
```

Commenting this line out results in errors saying 'ReferenceError: TeamCityReporter is not defined'.

**Comment by Sanjo** [comment]
That's how debugOnly: true package exports work. You need to use `api.use('sanjo:jasmine@0.20.3');` instead of `api.use('sanjo:jasmine@0.20.3', 'server');` btw. Otherwise CI running never finishes.

**Comment by vangorra** [comment]
Does the meteor project document this behavior with debug only?

Thanks for the tip on using server. In my ci scripts one disabled clients tests to handle the problem but will use your suggestion too.

**Comment by Sanjo** [comment]
> Does the meteor project document this behavior with debug only?

Yes, here: http://docs.meteor.com/#/full/pack_export

**Comment by vangorra** [comment]
I totally missed that part. My mistake.
