### ISSUE TITLE
jasmine with VELOCITY=0?

### ISSUE THREAD

**Issue by nilnullzip** [xolvio/meteor-jasmine#320]
I stumbled into this. I ran my usual jasmine CI test (meteor --test) with VELOCITY=1. Then I subsequently ran it with VELOCITY=0. I was surprised the find that the second test ran fine all my tests just fin. But it ran much quicker because it did not run velocity at all.

```
VELOCITY=1 meteor --test
VELOCITY=0 meteor --test
```

Don't know why, but from a reset project, I need to first run the VELOCITY=1 case first. Probably it is setting up some code that is needed subsequently.

Have I stumbled upon some kind of non-Velocity Jasmine CI mode? I am very interested. The time to start up VELOCITY has always been a problem for me. And I'd love to simplify the stack considering that the future of Velocity is uncertain.

**Comment by nilnullzip** [comment]
Indeed, I blew away `.meteor/local/mirrors` and `.meteor/local/db/meteor-jasmine*` after running `VELOCITY=1 meteor --test` and the subsequent `VELOCITY=0 meteor --test` worked great, apparently not using Velocity. Not sure where the interlock for allowing that second `meteor --test` exists.

```
VELOCITY=1 meteor --test
rm -rf .meteor/local/mirrors
rm -rf .meteor/local/db/meteor-jasmine*
VELOCITY=0 meteor --test
```

**Comment by Sanjo** [comment]
What Jasmine testing modes are you using?

**Comment by nilnullzip** [comment]
Server and client integration. Got tests in both modes. -Juan

**Comment by Sanjo** [comment]
I think the test results from the `VELOCITY=1 meteor --test` run are used. The test results are stored in the main app database. So this is not a speed up hack.

Avital works on testing improvements for Meteor 1.3. So this will hopefully be faster.

**Comment by nilnullzip** [comment]
That makes more sense! -Juan

-Juan
