### ISSUE TITLE
unit testing packages, and doing integration tests with cucumber

### ISSUE THREAD

**Issue by Alino** [xolvio/meteor-jasmine#322]
what do you recommend on how should we unit test meteor packages today?
I have written a lot of tests in jasmine, but in fact those are integration tests.
and my other question is: "should I use cucumber with chimp for integration tests instead of velocity jasmine integration tests?"
My idea is to:
1. abandon velocity jasmine integration test mode and write unit tests instead.
2. For integration tests, write cucumber only.

What do you think? :)

**Comment by Sanjo** [comment]
If you like Jasmine, I would recommend to continue writing unit and integration tests with Jasmine. And use chimp (Cucumber) for your acceptance tests. But you can also use Chimp for integration tests if you want.

Running server unit tests with sanjo:jasmine is currently not that fast (server-integration-mode). But when the testing improvements for Meteor 1.3 are done I will also look into making fast unit testing available as Meteor package.

With the app that we develop, we currently run the jasmine-server-integration mode and use the new unit testing scripts that I have just added publicly today here: https://github.com/xolvio/automated-testing-best-practices/tree/wip/migrate_1.3. They require your app to use ES2015 modules, but you could also load all app files in the right order. This is still work in progress, so unless you are willing to spend multiple hours, you may not touch it yet :-) The goal is to make it ready to use until Meteor 1.3 release.

**Comment by Sanjo** [comment]
And with the testing work that is currently done for Meteor 1.3, the execution of the tests will hopefully be faster.
