### ISSUE TITLE
error: Conflict: Constraint sanjo:jasmine@0.20.3 is not satisfied by sanjo:jasmine 0.1.17.

### ISSUE THREAD

**Issue by namirsab** [xolvio/meteor-jasmine#323]
When I try to use`sanjo:jasmine@0.20.3` in my `onTest` function in the `package.js` I cannot proceed with the test because of this error:
```
error: Conflict: Constraint sanjo:jasmine@0.20.3 is not satisfied by sanjo:jasmine 0.1.17.
   Constraints on package "sanjo:jasmine":
   * sanjo:jasmine@0.20.3 <- local-test:mypackage:mypackage0.0.1
```
This is my package.js file
```javascript
Package.onUse(function (api) {
    api.versionsFrom('1.2.0.2');
    api.use('ecmascript');
    ....
    ....
});

Package.onTest(function (api) {
    api.use('ecmascript');
    api.use('mypackage:mypackage');
    api.use('sanjo:jasmine@0.20.3');


    api.addFiles([
    ....
    ], 'server');
});
```
I have no other packages using any sanjo:jasmine package, and no global dependencies on velocity or whatever.

**Comment by Sanjo** [comment]
Not sure if that's the cause, but sanjo:jasmine@0.20.3 has a dependency on Meteor 1.2.1, so that's the minimum required version.

**Comment by namirsab** [comment]
Okey that make sense. Thanks!
