### ISSUE TITLE
spyOn not working with js methods inside iron router action (Server Integration)

### ISSUE THREAD

**Issue by ziedmahdi** [xolvio/meteor-jasmine#325]
I'm trying to write test for a twilio application. My strategy is to make a http request to my server, like what twilio will do when receiving a phone call on one of my numbers, then analyze the xml retrieved from the server response.

I tried to stub Meteor.users.find. But, I didn't succeed. The call to Meteor.users.find is from a route action. I thought maybe there is a problem with spyOn and functions inside routes actions.

 So, to investigate more in the problem. I decided to make the problem simpler. Here is the code:
 in `/server/routes.js`

```javascript
ExpertTest = {
    foo: function () {
        console.log("called");
        return 4;
    }
};


allo = function () {
    var res = ExpertTest.foo();
    console.log(res);
    
};

Router.route('/call-api/intro', {
    where: "server",
    name: "Intro",
    action: function () {        
        ExpertTest.foo();

        this.response.writeHead(200, {'Content-Type': 'application/xml; charset=utf-8'});
        this.response.end();
    }
});

```

and in `tests/jasmine/server/integration/IVRSpec.js`

```javascript
describe("With our IVR", function () {
    
    it("green test", function () {
        spyOn(ExpertTest, "foo").and.returnValue(50);
        
        allo();
        
        expect(ExpertTest.foo).toHaveBeenCalled();
        
    });




    it('red test', function() {
        spyOn(ExpertTest, "foo").and.returnValue(50);
        
        var callFirstResult = HTTP.get(baseUrl + '/call-api/intro');
        
        expect(ExpertTest.foo).toHaveBeenCalled();
    });

});

```

and here is the **error** in console: 

``` 
jasmine-server-integration: 1 tests failed
With our IVR red test
Expected spy foo to have been called.
meteor://💻app/tests/jasmine/server/integration/IVRSpec.js:81:32: Expected spy foo to have been called.
```

Did I do something wrong?

Can anyone help me?

Thank you very much

**Comment by Sanjo** [comment]
Where is baseUrl defined?

**Comment by ziedmahdi** [comment]
`baseUrl` is defined in  `tests/jasmine/server/integration/IVRSpec.js`. 

`var baseUrl = http://localhost:3000/;`

the `HTTP.get` call return correctly, no error is thrown. But, the test fails. 

```
jasmine-server-integration: 1 tests failed
With our IVR red test
Expected spy foo to have been called.
meteor://💻app/tests/jasmine/server/integration/IVRSpec.js:81:32: Expected spy foo to have been called.
```

Thank you for the help.

**Comment by Sanjo** [comment]
Set baseUrl to `process.env.ROOT_URL`. The tests run in a separate instance of your app, on another port.

**Comment by ziedmahdi** [comment]
@Sanjo the problem is not related to `baseUrl`. I deleted the variable `baseUrl`and replaced the string in `Http.get` like above.

```javascript
var callFirstResult = HTTP.get('http://localhost:8080/call-api/intro');

```

The test still failing with the same error.
 
I created a C9 workspace. You can inspect it here [https://ide.c9.io/ziedmahdi/jasmine-problem
](url)

**Comment by Sanjo** [comment]
Do `var callFirstResult = HTTP.get(Meteor.absoulteUrl('call-api/intro');` or `var callFirstResult = HTTP.get(process.env.ROOT_URL + 'call-api/intro');`. I think you still do the request to your main app instance and not the testing app instance where the spyOn is active.

**Comment by Sanjo** [comment]
This might also be relevant for C9. https://forums.meteor.com/t/testing-with-velocity-on-c9-io/17374.

**Comment by ziedmahdi** [comment]
@Sanjo Your suggestion is correct.

**Comment by ziedmahdi** [comment]
So finally, here is the wright solution (provided by @Sanjo)

`var callFirstResult = HTTP.get(process.env.ROOT_URL + 'firstRoute');`

or 

`var callFirstResult = HTTP.get(Meteor.absoluteUrl('firstRoute'));`
