### ISSUE TITLE
Why use preprocessors to support languages like coffeescript?

### ISSUE THREAD

**Issue by vangorra** [xolvio/meteor-jasmine#326]
Looking through the source, I notice karma preprocessors are being used to support coffeescript. What is preventing us from using Meteor's compilers to compile test.coffee into test.js and run that?

This approach has several advantages:
- Dev can write tests in the language the app is written in.
- Transpiled files are processed in the same manner with the same config as the app. This is especially important for language like typescript that have very flexible compile options.
- Less effort in supporting other languages in the future.
- A potentially less smaller meteor-jasmine code footprint as we only need to support es5.

**Comment by Sanjo** [comment]
Mainly the missing support to compile tests files without automatically including them in the app.
I will make Avital aware of this, so it is considered for the Meteor 1.3 unit test mode.

**Comment by vangorra** [comment]
I read a post where you and avital were discussing testing modes but nothing was concretely stated. Is velocity getting merged into meteor or something?
