### ISSUE TITLE
Client Unit testing doesn't run

### ISSUE THREAD

**Issue by khaledkbadr** [xolvio/meteor-jasmine#327]
I have client's unit testing that doesn't running by default. I have to click "debug" in the Karma pop-up window so it can run. Also it doesn't detect any change in my code when I do that.

**Comment by Sanjo** [comment]
* Maybe you have some code that prevents running your app inside an iFrame?
* Maybe you have to disable your router if you don't use iron router.
* Have a look in the .meteor/local/log/ log file for client unit mode.
