### ISSUE TITLE
window.jasmine is not defined until runTests()

### ISSUE THREAD

**Issue by kamilkisiela** [xolvio/meteor-jasmine#332]
Jasmine's interface is being added to `global` inside `runTests()` ([see here](https://github.com/xolvio/meteor-jasmine/blob/master/src/client/runTests.js#L10))

```javascript
console.log(window.jasmine); // undefined

describe('this weekend', function() {
  console.log(window.jasmine); // defined

  it('should be amazing', function() {
    expect(weekend).toBe(amazing);
  });
});
```

Let's say someone is using `angular-mocks`. 

It won't work anymore because it's checking if `window.jasmine` or `window.mocha` is available ([see here](https://github.com/angular/angular.js/blob/master/src/ngMock/angular-mocks.js#L2567)).

**Comment by kamilkisiela** [comment]
@Sanjo I'm going to work on it tomorrow

**Comment by Sanjo** [comment]
Ok.
