### ISSUE TITLE
Migration to Meteor 1.3 - using without Velocity

### ISSUE THREAD

**Issue by edwardupton** [xolvio/meteor-jasmine#334]
I'm confused as to how your package is supposed to behave with the new Meteor test framework.

If I run `meteor test --driver-package sanjo:jasmine --port 4000` is it supposed to provide a web reporting framework, like the pacticalmeteor:mocha package?  I don't get any console or browser messages.

Or is it still only working with Velocity html-reporter.  In which case that has now broken, and there's no documentation on how to fix it.  The link in history.md to https://github.com/xolvio/automated-testing-best-practices/tree/wip/migrate_1.3 is broken.

**Comment by Sanjo** [comment]
The sanjo:jasmine package is still working with the velocity:html-reporter and velocity:console-reporter (documented at https://github.com/xolvio/meteor-jasmine#installation). Make sure that velocity:html-reporter@0.10.0 is installed. Previous versions are not working.

**Comment by edwardupton** [comment]
I’ve definitely got the up to date velocity packages running

`
velocity:chokidar@1.2.0_1
velocity:core@0.10.10
velocity:html-reporter@0.10.0
velocity:meteor-internals@1.1.0_7
sanjo:jasmine@1.0.0
sanjo:long-running-child-process@1.1.5
sanjo:meteor-files-helpers@1.2.0_1
sanjo:meteor-version@1.0.0
`

But since the Meteor update it just doesn’t trigger the mirrors or Karma.
I guess it’s some issue with velocity core, or do I need to change a
setting?

On Mon, Apr 11, 2016 at 6:58 PM, Jonas Aschenbrenner <
notifications@github.com> wrote:

> The sanjo:jasmine package is still working with the velocity:html-reporter
> and velocity:console-reporter (documented at
> https://github.com/xolvio/meteor-jasmine#installation). Make sure that
> velocity:html-reporter@0.10.0 is installed. Previous versions are not
> working.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xolvio/meteor-jasmine/issues/334#issuecomment-208476370>
>



-- 
Edward Upton
Founder, LittleData
<http://www.littledata.co.uk/?utm_source=email&utm_campaign=email_signature>

LittleData is a Google Analytics Consulting Partner
<https://www.google.com/analytics/partners/company/5154876254322688/gacp/5730192894984192/service/5748755743637504>
 & Technology Partner
<https://www.google.com/analytics/partners/company/5154876254322688/gadp/5629499534213120/app/5707702298738688/listing/5649050225344512>

skype: edwardupton | @littledatauk <https://twitter.com/littledatauk> |
LinkedIn <https://www.linkedin.com/company/littledata>

Phone: +44 20 8050 2081
Office: Kensington Aldridge Academy, Silchester Road, London

**Comment by Sanjo** [comment]
velocity:core should no longer be a dependency, instead you should see velocity:reports. So maybe you need to remove velocity:core from '.meteor/packages'.

Also note that tests that are in a /tests/ folder will not get picked up. You need to move them somewhere else. And you need to test extensions that are documented in the Meteor Guide testing section.

**Comment by zenweasel** [comment]
Are you saying that tests in a `tests` folder are being ignored, or that they won't be picked up unless they have the `test/app-test` naming?

**Comment by zenweasel** [comment]
Also, for anybody else who encounters this, if you have `practicalmeteor:mocha` installed it seems to cause problems (`ClientServerReporter.constructor: Missing reporter to run tests. Use MochaRunner.setReporter(reporter) to set one.`)

**Comment by edwardupton** [comment]
Thanks both - that’s the answer I was looking for: that you need the new
.test.js extension, but can still use Velocity.

The issue is that Velocity is just not firing up (no dot in the top right
of the browser window) - I assume if it couldn’t find the tests, then it
would show the buttons to add some example tests.

I haven’t got practical meteor:mocha, and I think these and the correct
packages:
`
sanjo:jasmine@1.0.0
velocity:html-reporter@0.10.0
velocity:reports@1.0.0
`

What else could be going wrong?

On Tue, Apr 12, 2016 at 7:18 AM, Brent Hoover <notifications@github.com>
wrote:

> Also, for anybody else who encounters this, if you have
> practicalmeteor:mocha installed it seems to cause problems (ClientServerReporter.constructor:
> Missing reporter to run tests. Use MochaRunner.setReporter(reporter) to set
> one.)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xolvio/meteor-jasmine/issues/334#issuecomment-208725856>
>



-- 
Edward Upton
Founder, LittleData
<http://www.littledata.co.uk/?utm_source=email&utm_campaign=email_signature>

LittleData is a Google Analytics Consulting Partner
<https://www.google.com/analytics/partners/company/5154876254322688/gacp/5730192894984192/service/5748755743637504>
 & Technology Partner
<https://www.google.com/analytics/partners/company/5154876254322688/gadp/5629499534213120/app/5707702298738688/listing/5649050225344512>

skype: edwardupton | @littledatauk <https://twitter.com/littledatauk> |
LinkedIn <https://www.linkedin.com/company/littledata>

Phone: +44 20 8050 2081
Office: Kensington Aldridge Academy, Silchester Road, London

**Comment by zenweasel** [comment]
@edwardupton I am running this locally and it is working for me now. I have a folder called `apptests` with a test called `dummy.test.js`. 
```
I20160413-08:43:19.770(8)? jasmine-server: 1 tests passed (0ms)
I20160413-08:43:19.888(8)? jasmine-client: 1 tests passed (3ms)
```
What are you seeing?

**Comment by zenweasel** [comment]
Should this be working `test-packages` as well? Running that I get
```
meteor.js?hash=199010c…:1008 Uncaught Error: Test driver package sanjo:jasmine missing `runTests` export
```

**Comment by Sanjo** [comment]
@zenweasel I have just updated the example for package testing. It works. See: 
https://github.com/xolvio/meteor-jasmine/commit/d01df1027d87bb9c7403c9bde531b82c0bf5c27a

**Comment by zenweasel** [comment]
@Sanjo Got it. Thanks!

**Comment by Sanjo** [comment]
I've updated the README to contain all the essential infos: https://atmospherejs.com/sanjo/jasmine. Let me know if there is still something unclear.
