### ISSUE TITLE
How to test collection.allow?

### ISSUE THREAD

**Issue by stewiegaribaldi** [xolvio/meteor-jasmine#337]
I have been trying to test collection.allow using jasmine but without success. I found [this](http://stackoverflow.com/questions/28226969/testing-meteor-testing-allow-deny-with-a-unit-test-instead-of-integration-te/28378940#28378940)  but I got Cannot call method 'insert' of null. Any one has example? Thank you.

**Comment by Sanjo** [comment]
Please ask in the other places mentioned here: https://github.com/xolvio/meteor-jasmine#free-support because this is a general Meteor testing question. Thanks.
